# Generated by Django 5.0.3 on 2024-04-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='id_cours',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
