# Generated by Django 5.0.3 on 2024-04-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_alter_cours_id_cours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='type_fichier',
        ),
        migrations.AlterField(
            model_name='cours',
            name='nom_cours',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
