# Generated by Django 5.0.3 on 2024-04-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_remove_solution_type_fichier_alter_cours_nom_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
