# Generated by Django 5.0.3 on 2024-05-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0004_cours_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='nom_exercice',
            field=models.CharField(default='Exercice sans nom', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
