# Generated by Django 5.0.3 on 2024-05-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0005_exercice_nom_exercice_exercice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='nom_exercice',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
