# Generated by Django 5.0.3 on 2024-05-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0006_alter_exercice_nom_exercice'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
