# Generated by Django 5.0.3 on 2024-05-15 09:53

import django.db.models.deletion
import programmes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0007_solution_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('slug', models.SlugField(blank=True, null=True)),
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.FileField(blank=True, upload_to=programmes.models.save_reponce, verbose_name='reponce')),
                ('créer_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.exercice')),
            ],
        ),
    ]
