# Generated by Django 5.0.3 on 2024-05-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0008_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='id_cours',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cours',
            name='nom_cours',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
