# Generated by Django 5.0.3 on 2024-05-29 22:21

import programmes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0009_alter_cours_id_cours_alter_cours_nom_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='fichier',
            field=models.FileField(upload_to=programmes.models.save_cours, verbose_name='fichier'),
        ),
    ]
