# Generated by Django 5.0.3 on 2024-05-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0010_alter_cours_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='video',
        ),
    ]
