# Generated by Django 5.0.3 on 2024-06-08 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0011_remove_cours_video'),
        ('utilisateurs', '0007_alter_eleve_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='créer_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.enseignant'),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='créer_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.enseignant'),
        ),
    ]
