# Generated by Django 5.0.3 on 2024-05-22 10:56

import utilisateurs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_enseignant_numero_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=utilisateurs.models.path_and_rename, verbose_name='Profile Picture'),
        ),
    ]
