# Generated by Django 5.0.3 on 2024-05-23 10:27

import utilisateurs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_eleve_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=utilisateurs.models.path_and_rename, verbose_name='Profile Picture'),
        ),
    ]
