# Generated by Django 5.0.3 on 2024-05-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_enseignant_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
