# Generated by Django 5.0.3 on 2024-06-08 15:12

import utilisateurs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_alter_eleve_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/Images/photo.jpg', upload_to=utilisateurs.models.path_and_rename, verbose_name='Profile Picture'),
        ),
    ]
